<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../css/style.css">
</head>
<body>
    <main class="content">
        <h1 title >Olá mundo</h1>
        <div class="users">
            <h2 class="subtitle">Usuarios</h2>
            <? foreach($this->view->users as $key => $value){?>
            <div class="user">
                <p class="user-name"><?= $value['name'] ?></p>
            </div>
            <? } ?>
            
        </div>
        <a href="/sair">Sair</a>
    </main>
    
</body>
</html>