<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="/registrar" method="post">
        <input name="name" type="text" placeholder="nome">
        <input type="email" name="email" id="email" placeholder="email">
        <input type="password" name="pass" id="password" placeholder="senha">
        <input type="password" name="confirm_pass" id="confirm_password" placeholder="confirmar senha">
        <input type="submit" value="Criar Conta">
        <? if(isset($this->view->callback["success"]) && $this->view->callback["success"]){?>
            <p><?= $this->view->callback["message"]?></p>
        <? }?>
        <? if(isset($this->view->callback["success"]) && !$this->view->callback["success"]){?>
            <p><?= $this->view->callback["message"]?> error</p>
        <? }?>
    </form>
</body>
</html>