<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Sistema login e cadastro</title>
</head>
<body>
    <main class="content">
        <h1 class="title">Sistema Login Cadastro</h1>
        <a href="/conta/criar">Criar Conta</a>
        <a href="/conta/login">Entrar</a>
    </main>
    
</body>
</html>