<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="/login" method="POST">
        <input type="text" name="name" placeholder="nome">
        <input type="password" name="pass" id="" placeholder="senha">
        <input type="submit" value="Login">
        <? if(isset($this->view->callback["success"]) && $this->view->callback["success"]){?>
            <p><?= $this->view->callback["message"]?></p>
        <? }?>
        <? if(isset($this->view->callback["success"]) && !$this->view->callback["success"]){?>
            <p><?= $this->view->callback["message"]?> error</p>
        <? }?>
    </form>
</body>
</html>